### ISSUE TITLE
Problem: self.inputMin, inputMax are equal on some dataset

### ISSUE THREAD

**Issue by breznak** [htm-community/NAB#13]
A possible bug, the `self.inputMin, inputMax` is provided by the NAB API. 

- one some dataset (I don't know which) the values are all the same (ie the dataset is just a flat line) 

> 57: Results have been written to /mnt/store/devel/HTM/NAB/results/htmcore/realTweets/htmcore_Twitter_volume_UPS.csv
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
result = (True, func(*args, **kwds))
File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
return list(map(*args))
File "/mnt/store/devel/HTM/NAB/nab/detectors/base.py", line 147, in detectDataSet
detectorInstance.initialize()
File "/mnt/store/devel/HTM/NAB/nab/detectors/htmcore/htmcore_detector.py", line 284, in initialize
assert self.inputMin < self.inputMax, "FAILED "+str(self.inputMin)+" "+str(self.inputMax)
AssertionError: FAILED 45.0 45.0
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "run.py", line 247, in <module>
main(args)
File "run.py", line 96, in main
runner.detect(detectorConstructors)
File "/mnt/store/devel/HTM/NAB/nab/runner.py", line 134, in detect
self.pool.map_async(detectDataSet, args).get(99999999)
File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
raise self._value
AssertionError: FAILED 45.0 45.0

- our c++ `ScalarEncoder` has a check that `min < max`
  - which is reasonable, for otherwise the encoder would use `0` for some internal sizes. 

- I don't know if the problem is a bug in how this NAB implementation computes/deals with setting the min.max, 
- or if we have to workaround that in c++ ScalarEncoder?

**Comment by D-McDougall** [comment]
I think that this is a bug in NAB, or maybe the data set is a flat line at `45.0`?

**Comment by markNZed** [comment]
One of the timeseries https://github.com/htm-community/NAB/blob/master/data/artificialNoAnomaly/art_flatline.csv is a flat line - I guess to check that the detector does not create false positives.
