### ISSUE TITLE
Installation error in Windows

### ISSUE THREAD

**Issue by be4pro** [htm-community/NAB#20]
I was installing NAB in Win7 environment, the error came after running `python setup.py install`
>Using e:\python37\lib\site-packages
Finished processing dependencies for nab==1.0
The system cannot find the path specified.
python: can't open file 'nab/detectors/htmcore/setup.py': [Errno 2] No such file or directory

I had nab-1.0 in site-package folder and `pip list` can detect nab. How would it affect usage? (My guess is that I couldn't use htmcore as a detector)

By the way, I commented out `long_description=read("README.md")` in setup.py due to encoding issue(I got unicode value error and couldn't install it even I particularly `chcp 65001`). I don't know if it was related.

**Comment by be4pro** [comment]
I tested `py run.py -d htmcore --detect --windowsFile labels/combined_windows_tiny.json`. Aside from several no label warnings, I also got OverflowError as below:
>Running detection step
Traceback (most recent call last):
  File "run.py", line 247, in <module>
    main(args)
  File "run.py", line 96, in main
    runner.detect(detectorConstructors)
  File "D:\NAB-master\nab\runner.py", line 134, in detect
    self.pool.map_async(detectDataSet, args).get(99999999)
  File "E:\Python37\lib\multiprocessing\pool.py", line 651, in get
    self.wait(timeout)
  File "E:\Python37\lib\multiprocessing\pool.py", line 648, in wait
    self._event.wait(timeout)
  File "E:\Python37\lib\threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "E:\Python37\lib\threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
OverflowError: timeout value is too large
